"""
Embedding Provider Interface

Abstract base for embedding providers (OpenAI, Ollama, etc.)
Following the pattern from Llore.
"""

from abc import ABC, abstractmethod
from typing import List


class EmbeddingProvider(ABC):
    """Abstract base class for embedding providers."""

    @abstractmethod
    def create_embedding(self, text: str) -> List[float]:
        """Generate an embedding vector for the given text.

        Args:
            text: The text to embed

        Returns:
            List of floats representing the embedding vector
        """
        pass

    @abstractmethod
    def model_identifier(self) -> str:
        """Return a unique identifier for this provider/model combination.

        Used for the vector_version column to track which embeddings
        were generated by which provider.

        Returns:
            String like "openai:text-embedding-3-small" or "ollama:nomic-embed-text"
        """
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the dimension of embedding vectors from this provider.

        Returns:
            Integer dimension (e.g., 1536 for OpenAI text-embedding-3-small)
        """
        pass
